const prefix = "";
// const prefix = "/demo/zesty-zap/";
export const Images = {
  globeIcon: `${prefix}./image/globeIcon.png`,
  rightArrowIcon: `${prefix}./image/rightArrowIcon.png`,
  arrowNarrowRight: `${prefix}./image/arrowNarrowRight.png`,
  shopIcon: `${prefix}./image/shopIcon.png`,
  playImage: `${prefix}./image/playImage.png`,
  giftCardPlaneImage: `${prefix}./image/giftCardPlaneImage.png`,
  loanSectionImage: `${prefix}./image/loanSectionImage.png`,
  calculator: `${prefix}./image/calculator.png`,
  one: `${prefix}./image/ONE.png`,
  two: `${prefix}./image/two.png`,
  three: `${prefix}./image/three.png`,
  comfortableSectionPic: `${prefix}./image/comfortableSectionPic.png`,
  shopSectionImage2: `${prefix}./image/shopSectionImage2.png`,
  shopSectionImage: `${prefix}./image/shopSectionImage.png`,
  distributeSectionImage: `${prefix}./image/distributeSectionImage.png`,
  distributeSectionBackgroundImage: `${prefix}./image/distributeSectionBackgroundImage.png`,
  distributeSectionBackgroundImage1: `${prefix}./image/distributeSectionBackgroundImage1.png`,
  phoneRight: `${prefix}./image/phoneRight.png`,
  phoneLeft: `${prefix}./image/phoneLeft.png`,
  plusIcon: `${prefix}./image/plusIcon.png`,
  minusIcon: `${prefix}./image/minusIcon.png`,
  websiteLogo: `${prefix}./image/full-logo.png`,
  footerLogo: `${prefix}./image/footerLogo.png`,
  headerMenubarIcon: `${prefix}./image/small-logo.png`,
  netgiroTextLogo: `${prefix}./image/full-logo.png`,
  heroSection: `${prefix}./image/heroSection.avif`,
  sofa: `${prefix}./image/sofa.png`,
  jacket: `${prefix}./image/jacket.png`,
  camera: `${prefix}./image/camera.png`,
  shoe: `${prefix}./image/shoe.png`,
  coat: `${prefix}./image/coat.png`,
  tshirt: `${prefix}./image/tshirt.png`,
};
