import React from 'react';
import { webFontFamily } from './fonts';

export const typography:any = {
  headings: {
    en: {
      h1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '68px',
        lineHeight: '73px',
      } as React.CSSProperties,
      h2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: 'clamp(20px, calc(24 / 1366 * 100vw), 60px)',
        lineHeight: '35px',
      } as React.CSSProperties,
      h3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: 'clamp(20px, calc(42 / 1366 * 100vw), 62px)',
        lineHeight: '51px',
      } as React.CSSProperties,
      h4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: 'clamp(42px, calc(42 / 1366 * 100vw), 62px)',
        lineHeight: 'clamp(51px, calc(51 / 1366 * 100vw), 72px)',
      } as React.CSSProperties,
      h5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: 'clamp(40px, calc(42 / 1366 * 100vw), 62px)',
        lineHeight: '51px',
      } as React.CSSProperties,
      h6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '123px',
        lineHeight: '184px',
      } as React.CSSProperties,
      h7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '38px',
        lineHeight: '50px',
      } as React.CSSProperties,
    },
    ar: {
      h1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '68px',
        lineHeight: '73px',
      } as React.CSSProperties,
      h2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '24px',
        lineHeight: '35px',
      } as React.CSSProperties,
      h3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '42px',
        lineHeight: '51px',
      } as React.CSSProperties,
      h4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '42px',
        lineHeight: '51px',
      } as React.CSSProperties,
      h5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '40px',
        lineHeight: '51px',
      } as React.CSSProperties,
      h6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '123px',
        lineHeight: '184px',
      } as React.CSSProperties,
      h7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '38px',
        lineHeight: '50px',
      } as React.CSSProperties,
    },
  } ,
  paragraph: {
    en: {
      p1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: 'clamp(20px, calc(20 / 1366 * 100vw), 30px)',
        lineHeight: '40px',
      } as React.CSSProperties,
      p2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: 'clamp(20px, calc(20 / 1366 * 100vw), 30px)',
        lineHeight: '39px',
      } as React.CSSProperties,
      p3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: 'clamp(24px, calc(24 / 1366 * 100vw), 40px)',
        lineHeight: 'clamp(39px, calc(39 / 1366 * 100vw), 50px)',
      } as React.CSSProperties,
      p4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: 'clamp(24px, calc(24 / 1366 * 100vw), 60px)',
        lineHeight: '35px',
      } as React.CSSProperties,
      p5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '25px',
        lineHeight: '35px',
      } as React.CSSProperties,
      p6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '17px',
        lineHeight: '25px',
      } as React.CSSProperties,
      p7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: 'clamp(20px, calc(20 / 1366 * 100vw), 30px)',
        lineHeight: 'clamp(36px, calc(36 / 1366 * 100vw), 46px)',
      } as React.CSSProperties,
      p8: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: 'clamp(17px, calc(17 / 1366 * 100vw), 30px)',
        lineHeight: 'clamp(26px, calc(26 / 1366 * 100vw), 46px)',
      } as React.CSSProperties,
    },
    ar: {
      p1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '20px',
        lineHeight: '35px',
      } as React.CSSProperties,
      p2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '20px',
        lineHeight: '39px',
      } as React.CSSProperties,
      p3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '24px',
        lineHeight: '39px',
      } as React.CSSProperties,
      p4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '24px',
        lineHeight: '35px',
      } as React.CSSProperties,
      p5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '25px',
        lineHeight: '35px',
      } as React.CSSProperties,
      p6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '17px',
        lineHeight: '25px',
      } as React.CSSProperties,
      p7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: '20px',
        lineHeight: '36px',
      } as React.CSSProperties,
      p8: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontWeight: 300,
        fontSize: 'clamp(17px, calc(17 / 1366 * 100vw), 30px)',
        lineHeight: 'clamp(26px, calc(26 / 1366 * 100vw), 46px)',
      } as React.CSSProperties,
    },
  } ,
  buttonText: {
    en: {
      b1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: '14px',
        fontWeight: 600,
        lineHeight: '17px',
      } as React.CSSProperties,
      b2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: '13px',
        fontWeight: 400,
        lineHeight: '12px',
      } as React.CSSProperties,
      b3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(13px, calc(13 / 1366 * 100vw), 62px)',
        fontWeight: 600,
        lineHeight: '25px',
      } as React.CSSProperties,
      b4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(14px, calc(14 / 1366 * 100vw), 62px)',
        fontWeight: 600,
        lineHeight: '26px',
      } as React.CSSProperties,
      b5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(17px, calc(17 / 1366 * 100vw), 62px)',
        fontWeight: 700,
        lineHeight: '26px',
      } as React.CSSProperties,
      b6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(16px, calc(16 / 1366 * 100vw), 62px)',
        fontWeight: 500,
        lineHeight: '30px',
      } as React.CSSProperties,
      b7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(13px, calc(13 / 1366 * 100vw), 62px)',
        fontWeight: 500,
        lineHeight: '25px',
      } as React.CSSProperties,
    },
    ar: {
      b1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontSize: '22px',
        lineHeight: '28px',
        fontWeight: 700,
      } as React.CSSProperties,
      b2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: '13px',
        fontWeight: 400,
        lineHeight: '12px',
      } as React.CSSProperties,
      b3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(13px, calc(13 / 1366 * 100vw), 62px)',
        fontWeight: 600,
        lineHeight: '25px',
      } as React.CSSProperties,
      b4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(14px, calc(14 / 1366 * 100vw), 62px)',
        fontWeight: 600,
        lineHeight: '26px',
      } as React.CSSProperties,
      b5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(17px, calc(17 / 1366 * 100vw), 62px)',
        fontWeight: 600,
        lineHeight: '26px',
      } as React.CSSProperties,
      b6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(16px, calc(16 / 1366 * 100vw), 62px)',
        fontWeight: 500,
        lineHeight: '30px',
      } as React.CSSProperties,
      b7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Semi Bold',
        fontSize: 'clamp(14px, calc(16 / 1366 * 100vw), 62px)',
        fontWeight: 500,
        lineHeight: '26px',
      } as React.CSSProperties,
    },
  },
  label: {
    en: {
      l1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(14px, calc(14 / 1366 * 100vw), 24px)',
        lineHeight: '15px',
        fontWeight: 400,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(20px, calc(20 / 1366 * 100vw), 60px)',
        lineHeight: 'clamp(35px, calc(42 / 1366 * 100vw), 70px)',
        fontWeight: 700,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(15px, calc(15 / 1366 * 100vw), 60px)',
        lineHeight: 'clamp(15px, calc(22 / 1366 * 100vw), 70px)',
        fontWeight: 300,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(15px, calc(15 / 1366 * 100vw), 60px)',
        lineHeight: 'clamp(15px, calc(22 / 1366 * 100vw), 70px)',
        fontWeight: 400,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(13px, calc(13 / 1366 * 100vw), 60px)',
        lineHeight: 'clamp(15px, calc(22 / 1366 * 100vw), 70px)',
        fontWeight: 300,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(24px, calc(24 / 1366 * 100vw), 28px)',
        lineHeight: '40px',
        fontWeight: 700,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(18px, calc(18 / 1366 * 100vw), 22px)',
        lineHeight: '40px',
        fontWeight: 700,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l8: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: 'clamp(15px, calc(15 / 1366 * 100vw), 60px)',
        lineHeight: 'clamp(22px, calc(22 / 1366 * 100vw), 70px)',
        fontWeight: 400,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
    },
    ar: {
      l1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: '14px',
        lineHeight: '15px',
        fontWeight: 400,
      } as React.CSSProperties,
      l2: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: '20px',
        lineHeight: '35px',
        fontWeight: 700,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l3: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: '15px',
        lineHeight: '25px',
        fontWeight: 300,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l4: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: '15px',
        lineHeight: '25px',
        fontWeight: 400,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l5: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: '13px',
        lineHeight: '15px',
        fontWeight: 300,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l6: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: '24px',
        lineHeight: '40px',
        fontWeight: 700,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l7: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Regular',
        fontSize: '18px',
        lineHeight: '40px',
        fontWeight: 700,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
    },
  } ,
  inputFieldText: {
    en: {
      i1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'Medium',
        fontSize: '15px',
        lineHeight: '18px',
        fontWeight: 500,
      } as React.CSSProperties,
    },
    ar: {
      i1: {
        fontFamily: webFontFamily['ProximaNova-Regular'],
        fontStyle: 'normal',
        fontSize: '16px',
        lineHeight: '31px',
        fontHeight: 500,
      } as React.CSSProperties,
    },
  } ,
};
